version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bankapp_frontend
    restart: always
    ports:
      - 8000:8000
    # volumes:
      # - ./frontend:/usr/src/app
